ALTER TABLE series ADD COLUMN IF NOT EXISTS plan_status VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE series ADD COLUMN IF NOT EXISTS plan_json JSONB;
ALTER TABLE series ADD COLUMN IF NOT EXISTS plan_error TEXT NOT NULL DEFAULT '';
