"""Series handler for API endpoints
Handles HTTP requests for series management
"""

package handler

import (
    "net/http"
    "time"

    "github.com/gin-gonic/gin"
    "gorm.io/gorm"

    "cadensend/services/control-api/internal/service"
    "cadensend/services/control-api/internal/database"
)

// SeriesHandler handles HTTP requests for series management
type SeriesHandler struct {
    db *gorm.DB
}

// NewSeriesHandler creates a new series handler
func NewSeriesHandler(db *gorm.DB) *SeriesHandler {
    return &SeriesHandler{db: db}
}

// RegisterRoutes registers series routes
func (h *SeriesHandler) RegisterRoutes(router gin.IRouter, authMiddleware gin.HandlerFunc) {
    series := router.Group("/series")
    series.Use(authMiddleware)
    {
        series.POST("", h.CreateSeries)
        series.GET("/:id", h.GetSeries)
        series.PATCH("/:id", h.UpdateSeries)
        series.POST("/:id/plan", h.GeneratePlan)
        series.GET("/:id/issues", h.ListIssues)
        series.POST("/:id/activate", h.ActivateSeries)
        series.POST("/:id/pause", h.PauseSeries)
        series.POST("/:id/resume", h.ResumeSeries)
    }
}

// CreateSeries handles series creation
func (h *SeriesHandler) CreateSeries(c *gin.Context) {
    var req struct {
        Topic       string `json:"topic" binding:"required"`
        Goal        string `json:"goal" binding:"required"`
        Level       string `json:"level"`
        Timezone    string `json:"timezone" binding:"required"`
        BriefJSON   string `json:"brief_json" binding:"required"`
        CreatedBy   string `json:"created_by" binding:"required"`
    }

    if err := c.ShouldBindJSON(&req); err != nil {
        c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
        return
    }

    series := &service.Series{
        ID:           "", // Generated by DB or UUID
        WorkspaceID:  c.GetString("workspace_id"),
        Slug:         req.Topic + "-" + time.Now().Format("20060102-150405"),
        Topic:        req.Topic,
        Goal:         req.Goal,
        Level:        req.Level,
        Timezone:     req.Timezone,
        Status:       "draft",
        CreatedBy:    req.CreatedBy,
        CreatedAt:    time.Now(),
        UpdatedAt:    time.Now(),
    }

    if err := h.db.Create(series).Error; err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
       	return
    }

    c.JSON(http.StatusCreated, gin.H{"data": series})
}

// GetSeries retrieves a series by ID
func (h *SeriesHandler) GetSeries(c *gin.Context) {
    id := c.Param("id")
    var series service.Series

    if err := h.db.Where("id = ? AND deleted_at IS NULL", id).First(&series).Error; err != nil {
       	c.JSON(http.StatusNotFound, gin.H{"error": "series not found"})
       	return
    }

    c.JSON(http.StatusOK, gin.H{"data": series})
}

// UpdateSeries updates series fields
func (h *SeriesHandler) UpdateSeries(c *gin.Context) {
    id := c.Param("id")
    var req struct {
        Topic    *string `json:"topic"`
        Goal     *string `json:"goal"`
        Level    *string `json:"level"`
        Timezone *string `json:"timezone"`
    }

    if err := c.ShouldBindJSON(&req); err != nil {
        c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
       	return
    }

    updates := make(map[string]interface{})
    if req.Topic != nil {
        updates["topic"] = *req.Topic
    }
    if req.Goal != nil {
        updates["goal"] = *req.Goal
    }
    if req.Level != nil {
        updates["level"] = *req.Level
    }
    if req.Timezone != nil {
        updates["timezone"] = *req.Timezone
    }
    updates["updated_at"] = time.Now()

    result := h.db.Model(&service.Series{}).Where("id = ?", id).Updates(updates)
    if result.Error != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": result.Error.Error()})
      	return
    }

    c.JSON(http.StatusOK, gin.H{"message": "series updated"})
}

// GeneratePlan triggers plan generation for a series
func (h *SeriesHandler) GeneratePlan(c *gin.Context) {
    id := c.Param("id")

    // In a real implementation, this would trigger an async task
    // For now, we return a placeholder
    plan := &service.SeriesPlan{
        ID:         "plan-" + id,
        SeriesID:   id,
        Version:    1,
        Curriculum: service.Curriculum{
            Objective: "Learn the fundamentals",
            Outline:   []string{"Week 1: Introduction", "Week 2: Deep Dive", "Week 3: Advanced Topics", "Week 4: Capstone"},
        },
        CreatedAt: time.Now(),
        UpdatedAt: time.Now(),
    }

    c.JSON(http.StatusOK, gin.H{"data": plan})
}

// ListIssues lists issues for a series
func (h *SeriesHandler) ListIssues(c *gin.Context) {
    id := c.Param("id")
    var issues []service.Issue

    if err := h.db.Where("series_id = ? AND deleted_at IS NULL", id).
        Order("sequence_no ASC").Find(&issues).Error; err != nil {
       	c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
      	return
    }

    c.JSON(http.StatusOK, gin.H{"data": issues})
}

// ActivateSeries activates a series
func (h *SeriesHandler) ActivateSeries(c *gin.Context) {
    id := c.Param("id")

    result := h.db.Model(&service.Series{}).
        Where("id = ?", id).
        Updates(map[string]interface{}{
            "status":      "active",
            "updated_at": time.Now(),
        })

    if result.Error != nil {
       	c.JSON(http.StatusInternalServerError, gin.H{"error": result.Error.Error()})
      	return
    }

    c.JSON(http.StatusOK, gin.H{"message": "series activated"})
}

// PauseSeries pauses a series
func (h *SeriesHandler) PauseSeries(c *gin.Context) {
    id := c.Param("id")

    result := h.db.Model(&service.Series{}).
        Where("id = ?", id).
        Updates(map[string]interface{}{
            "status":      "paused",
            "updated_at": time.Now(),
        })

    if result.Error != nil {
       	c.JSON(http.StatusInternalServerError, gin.H{"error": result.Error.Error()})
      	return
    }

    c.JSON(http.StatusOK, gin.H{"message": "series paused"})
}

// ResumeSeries resumes a series
func (h *SeriesHandler) ResumeSeries(c *gin.Context) {
    id := c.Param("id")

    result := h.db.Model(&service.Series{}).
        Where("id = ?", id).
        Updates(map[string]interface{}{
            "status":      "active",
            "updated_at": time.Now(),
        })

    if result.Error != nil {
       	c.JSON(http.StatusInternalServerError, gin.H{"error": result.Error.Error()})
      	return
    }

    c.JSON(http.StatusOK, gin.H{"message": "series resumed"})
}