// Source handler for API endpoints
// Handles HTTP requests for source management

package handler

import (
    "net/http"
    "time"

    "github.com/gin-gonic/gin"
    "gorm.io/gorm"

    "cadensend/services/control-api/internal/service"
)

// SourceHandler handles HTTP requests for source management
type SourceHandler struct {
    db *gorm.DB
}

// NewSourceHandler creates a new source handler
func NewSourceHandler(db *gorm.DB) *SourceHandler {
    return &SourceHandler{db: db}
}

// RegisterRoutes registers source routes
func (h *SourceHandler) RegisterRoutes(router gin.IRouter, authMiddleware gin.HandlerFunc) {
    sources := router.Group("/sources")
    sources.Use(authMiddleware)
    {
        sources.POST("/uploads", h.UploadSource)
        sources.POST("/urls", h.SubmitURL)
        sources.GET("", h.ListSources)
        sources.GET("/:id", h.GetSource)
        sources.GET("/:id/preview", h.PreviewSource)
        sources.POST("/:id/reindex", h.ReindexSource)
        sources.DELETE("/:id", h.DeleteSource)
    }
}

// SubmitURL handles URL source submission
func (h *SourceHandler) SubmitURL(c *gin.Context) {
    var req struct {
        URL     string `json:"url" binding:"required,url"`
        Type    string `json:"type" binding:"required"`
        Scope   string `json:"scope"`
    }

    if err := c.ShouldBindJSON(&req); err != nil {
        c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
       	return
    }

    source := &service.Source{
        ID:            "", // Generated by DB
        WorkspaceID:   c.GetString("workspace_id"),
        Scope:         req.Scope,
        Type:          req.Type,
        URL:           req.URL,
        Status:        "pending",
        CreatedBy:     c.GetString("user_id"),
        CreatedAt:     time.Now(),
        UpdatedAt:     time.Now(),
    }

    if err := h.db.Create(source).Error; err != nil {
       	c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
      	return
    }

    // In a real implementation, this would trigger async ingestion via the AI engine
    c.JSON(http.StatusCreated, gin.H{"data": source})
}

// UploadSource handles file upload
func (h *SourceHandler) UploadSource(c *gin.Context) {
    file, err := c.FormFile("file")
    if err != nil {
       	c.JSON(http.StatusBadRequest, gin.H{"error": "file is required"})
      	return
    }

    source := &service.Source{
        ID:            "",
        WorkspaceID:   c.GetString("workspace_id"),
        Scope:         c.PostForm("scope"),
        Type:          "file",
        Status:        "pending",
        CreatedBy:     c.GetString("user_id"),
        CreatedAt:     time.Now(),
        UpdatedAt:     time.Now(),
    }

    if err := h.db.Create(source).Error; err != nil {
       	c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
      	return
    }

    c.JSON(http.StatusCreated, gin.H{"data": source})
}

// ListSources lists all sources for workspace
func (h *SourceHandler) ListSources(c *gin.Context) {
    var sources []service.Source

    if err := h.db.Where("workspace_id = ? AND deleted_at IS NULL", c.GetString("workspace_id")).
        Find(&sources).Error; err != nil {
       	c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
      	return
    }

    c.JSON(http.StatusOK, gin.H{"data": sources})
}

// GetSource retrieves a source by ID
func (h *SourceHandler) GetSource(c *gin.Context) {
    id := c.Param("id")
    var source service.Source

    if err := h.db.Where("id = ? AND workspace_id = ? AND deleted_at IS NULL", id, c.GetString("workspace_id")).
        First(&source).Error; err != nil {
       	c.JSON(http.StatusNotFound, gin.H{"error": "source not found"})
      	return
    }

    c.JSON(http.StatusOK, gin.H{"data": source})
}

// PreviewSource returns a preview of source content
func (h *SourceHandler) PreviewSource(c *gin.Context) {
    id := c.Param("id")

    c.JSON(http.StatusOK, gin.H{
        "message": "preview not implemented in MVP",
        "source_id": id,
    })
}

// ReindexSource triggers re-indexing of a source
func (h *SourceHandler) ReindexSource(c *gin.Context) {
    id := c.Param("id")

    result := h.db.Model(&service.Source{}).
        Where("id = ?", id).
        Update("status", "pending")

    if result.Error != nil {
       	c.JSON(http.StatusInternalServerError, gin.H{"error": result.Error.Error()})
      	return
    }

    c.JSON(http.StatusOK, gin.H{"message": "reindex started"})
}

// DeleteSource soft deletes a source
func (h *SourceHandler) DeleteSource(c *gin.Context) {
    id := c.Param("id")

    now := time.Now()
    result := h.db.Model(&service.Source{}).
        Where("id = ? AND workspace_id = ?", id, c.GetString("workspace_id")).
        Update("deleted_at", now)

    if result.Error != nil {
       	c.JSON(http.StatusInternalServerError, gin.H{"error": result.Error.Error()})
      	return
    }

    if result.RowsAffected == 0 {
       	c.JSON(http.StatusNotFound, gin.H{"error": "source not found"})
      	return
    }

    c.JSON(http.StatusOK, gin.H{"message": "source deleted"})
}
