// Package auth provides authentication utilities for the control API
package auth

import (
    "crypto/rand"
    "crypto/sha256"
    "encoding/hex"
    "errors"
    "fmt"
    "time"

    "github.com/golang-jwt/jwt/v5"
    "golang.org/x/crypto/bcrypt"
)

// Claims represents JWT claims
type Claims struct {
    UserID      string `json:"user_id"`
    WorkspaceID string `json:"workspace_id"`
    Email       string `json:"email"`
    Role        string `json:"role"`
    jwt.RegisteredClaims
}

// User represents an authenticated user
type User struct {
    ID              string     `json:"id"`
    Email           string     `json:"email"`
    PasswordHash    string     `json:"-"`
    Name            string     `json:"name"`
    Timezone        string     `json:"timezone"`
    Status          string     `json:"status"`
    WorkspaceID     string     `json:"workspace_id"`
    CreatedAt       time.Time  `json:"created_at"`
    UpdatedAt       time.Time  `json:"updated_at"`
    DeletedAt       *time.Time `json:"deleted_at,omitempty"`
    EmailVerified   bool       `json:"email_verified"`
}

// MagicLinkToken represents a passwordless authentication token
type MagicLinkToken struct {
    Token     string     `json:"token"`
    UserID    string     `json:"user_id"`
    ExpiresAt time.Time  `json:"expires_at"`
    CreatedAt time.Time  `json:"created_at"`
}

// CreateUser creates a new user with hashed password
func CreateUser(email, password, name, timezone, workspaceID string) (*User, error) {
    passwordHash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
    if err != nil {
        return nil, fmt.Errorf("failed to hash password: %w", err)
    }

    return &User{
        ID:              "", // Will be generated by DB
        Email:           email,
        PasswordHash:    string(passwordHash),
        Name:            name,
        Timezone:        timezone,
        Status:          "active",
        WorkspaceID:     workspaceID,
        EmailVerified:   false,
    }, nil
}

// AuthenticateUser validates email and password
func AuthenticateUser(user *User, password string) error {
    if err := bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(password)); err != nil {
        return errors.New("invalid credentials")
    }
    return nil
}

// GenerateJWT creates a JWT token
func GenerateJWT(user *User, secret string, expiry time.Duration) (string, error) {
    claims := &Claims{
        UserID:      user.ID,
        WorkspaceID: user.WorkspaceID,
        Email:       user.Email,
        Role:        "user",
        RegisteredClaims: jwt.RegisteredClaims{
            IssuedAt:  jwt.NewNumericDate(time.Now()),
            ExpiresAt: jwt.NewNumericDate(time.Now().Add(expiry)),
            Issuer:    "cadensend",
        },
    }

    token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
    return token.SignedString([]byte(secret))
}

// ValidateJWT validates a JWT token and returns claims
func ValidateJWT(tokenString, secret string) (*Claims, error) {
    token, err := jwt.ParseWithClaims(tokenString, &Claims{}, func(token *jwt.Token) (interface{}, error) {
        if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
            return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
        }
        return []byte(secret), nil
    })

    if err != nil {
        return nil, err
    }

    if claims, ok := token.Claims.(*Claims); ok && token.Valid {
        return claims, nil
    }

    return nil, errors.New("invalid token")
}

// GenerateMagicLink generates a cryptographically secure token
func GenerateMagicLink() (string, error) {
    tokenBytes := make([]byte, 32)
    if _, err := rand.Read(tokenBytes); err != nil {
        return "", fmt.Errorf("failed to generate token: %w", err)
    }
    return hex.EncodeToString(tokenBytes), nil
}

// HashSHA256 generates a SHA-256 hash
func HashSHA256(data string) string {
    hash := sha256.Sum256([]byte(data))
    return hex.EncodeToString(hash[:])
}
